"""0001 initial schema

Revision ID: 0f0dad927b76
Revises: 
Create Date: 2026-04-25 20:34:55.848622+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f0dad927b76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lista', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lista', 'valor', name='uq_catalogos_lista_valor')
    )
    op.create_index('idx_catalogos_lista_activo', 'catalogos', ['lista', 'activo'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cod_usuario', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rol IN ('admin', 'operadora')", name='ck_users_rol_valido'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_username_activo', 'users', ['username', 'activo'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cod_cliente', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('phone_e164', sa.String(), nullable=True),
    sa.Column('email_lower', sa.String(), nullable=True),
    sa.Column('email_hash_sha256', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('canal_adquisicion', sa.String(), nullable=True),
    sa.Column('utm_source_at_capture', sa.String(), nullable=True),
    sa.Column('utm_medium_at_capture', sa.String(), nullable=True),
    sa.Column('utm_campaign_at_capture', sa.String(), nullable=True),
    sa.Column('utm_content_at_capture', sa.String(), nullable=True),
    sa.Column('utm_term_at_capture', sa.String(), nullable=True),
    sa.Column('fbclid_at_capture', sa.String(), nullable=True),
    sa.Column('gclid_at_capture', sa.String(), nullable=True),
    sa.Column('tratamiento_interes', sa.String(), nullable=True),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('cod_lead_origen', sa.String(), nullable=True),
    sa.Column('vtiger_lead_id_origen', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('merged_to', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_to'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_cliente')
    )
    op.create_index('idx_clientes_email_lower', 'clientes', ['email_lower'], unique=False)
    op.create_index('idx_clientes_nombre_lower', 'clientes', ['nombre'], unique=False)
    op.create_index('idx_clientes_phone_e164', 'clientes', ['phone_e164'], unique=False)
    op.create_table('dedup_candidates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('nuevo_id', sa.BigInteger(), nullable=False),
    sa.Column('nuevo_tipo', sa.String(), nullable=False),
    sa.Column('existente_id', sa.BigInteger(), nullable=False),
    sa.Column('existente_tipo', sa.String(), nullable=False),
    sa.Column('razon', sa.String(), nullable=False),
    sa.Column('score_similitud', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.Column('resolucion', sa.String(), nullable=True),
    sa.Column('resuelto_por', sa.BigInteger(), nullable=True),
    sa.Column('resuelto_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resuelto_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dedup_candidates_resuelto', 'dedup_candidates', ['resuelto'], unique=False)
    op.create_table('gastos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('num_secuencial', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('destinatario', sa.String(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('idx_user_sessions_token_active', 'user_sessions', ['session_token'], unique=False)
    op.create_index('idx_user_sessions_user_created', 'user_sessions', ['user_id', 'created_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_username', sa.String(), nullable=True),
    sa.Column('user_role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.BigInteger(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_occurred', 'audit_log', ['action', 'occurred_at'], unique=False)
    op.create_index('idx_audit_category_occurred', 'audit_log', ['category', 'occurred_at'], unique=False)
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index('idx_audit_occurred', 'audit_log', ['occurred_at'], unique=False)
    op.create_index('idx_audit_user_occurred', 'audit_log', ['user_id', 'occurred_at'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cod_lead', sa.String(), nullable=False),
    sa.Column('vtiger_id', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('phone_e164', sa.String(), nullable=False),
    sa.Column('email_lower', sa.String(), nullable=True),
    sa.Column('email_hash_sha256', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('canal_adquisicion', sa.String(), nullable=True),
    sa.Column('utm_source_at_capture', sa.String(), nullable=True),
    sa.Column('utm_medium_at_capture', sa.String(), nullable=True),
    sa.Column('utm_campaign_at_capture', sa.String(), nullable=True),
    sa.Column('utm_content_at_capture', sa.String(), nullable=True),
    sa.Column('utm_term_at_capture', sa.String(), nullable=True),
    sa.Column('fbclid_at_capture', sa.String(), nullable=True),
    sa.Column('gclid_at_capture', sa.String(), nullable=True),
    sa.Column('tratamiento_interes', sa.String(), nullable=True),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado_lead', sa.String(), nullable=False),
    sa.Column('fecha_captura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scoring_signals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('intent_level', sa.String(), nullable=True),
    sa.Column('nurture_state', sa.String(), nullable=False),
    sa.Column('nurture_stream', sa.String(), nullable=True),
    sa.Column('handoff_to_doctora_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handoff_status', sa.String(), nullable=True),
    sa.Column('handoff_notified_via', sa.String(), nullable=True),
    sa.Column('es_reactivacion', sa.Boolean(), nullable=False),
    sa.Column('cod_cliente_vinculado', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("estado_lead IN ('nuevo', 'contactado', 'agendado', 'asistio', 'cliente', 'perdido')", name='ck_leads_estado_valido'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_leads_score_rango'),
    sa.ForeignKeyConstraint(['cod_cliente_vinculado'], ['clientes.cod_cliente'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_lead')
    )
    op.create_index('idx_leads_email_lower', 'leads', ['email_lower'], unique=False)
    op.create_index('idx_leads_estado_score', 'leads', ['estado_lead', 'score'], unique=False)
    op.create_index('idx_leads_phone_e164', 'leads', ['phone_e164'], unique=False)
    op.create_index('idx_leads_vtiger_id', 'leads', ['vtiger_id'], unique=False)
    op.create_table('pagos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('num_secuencial', sa.Integer(), nullable=True),
    sa.Column('cod_pago', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cod_cliente', sa.String(), nullable=False),
    sa.Column('cliente_nombre', sa.String(), nullable=True),
    sa.Column('cod_item', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yape', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('plin', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('giro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_pago', sa.String(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo_pago IN ('normal', 'credito_generado', 'credito_aplicado', 'abono_deuda')", name='ck_pagos_tipo_valido'),
    sa.ForeignKeyConstraint(['cod_cliente'], ['clientes.cod_cliente'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_pago')
    )
    op.create_index('idx_pagos_cod_cliente_fecha', 'pagos', ['cod_cliente', 'fecha'], unique=False)
    op.create_index('idx_pagos_cod_item', 'pagos', ['cod_item'], unique=False)
    op.create_index('idx_pagos_tipo_pago', 'pagos', ['tipo_pago'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('num_secuencial', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cod_cliente', sa.String(), nullable=False),
    sa.Column('cliente_nombre', sa.String(), nullable=True),
    sa.Column('cliente_telefono', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('cod_item', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('zona_cantidad_envase', sa.String(), nullable=True),
    sa.Column('proxima_cita', sa.Date(), nullable=True),
    sa.Column('fecha_nac_cliente', sa.Date(), nullable=True),
    sa.Column('moneda', sa.String(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yape', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('plin', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('giro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('debe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pagado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tc', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('precio_lista', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('Tratamiento', 'Producto', 'Certificado', 'Promocion')", name='ck_ventas_tipo_valido'),
    sa.ForeignKeyConstraint(['cod_cliente'], ['clientes.cod_cliente'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ventas_cod_cliente_fecha', 'ventas', ['cod_cliente', 'fecha'], unique=False)
    op.create_index('idx_ventas_cod_item', 'ventas', ['cod_item'], unique=False)
    op.create_index('idx_ventas_fecha', 'ventas', ['fecha'], unique=False)
    op.create_table('lead_touchpoints',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('fecha_contacto', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_medium', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('utm_content', sa.String(), nullable=True),
    sa.Column('utm_term', sa.String(), nullable=True),
    sa.Column('fbclid', sa.String(), nullable=True),
    sa.Column('gclid', sa.String(), nullable=True),
    sa.Column('primer_mensaje', sa.Text(), nullable=True),
    sa.Column('form_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("canal IN ('form_web', 'whatsapp_cloud_api')", name='ck_lead_touchpoints_canal_valido'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_touchpoints_fecha', 'lead_touchpoints', ['fecha_contacto'], unique=False)
    op.create_index('idx_lead_touchpoints_lead_fecha', 'lead_touchpoints', ['lead_id', 'fecha_contacto'], unique=False)
    op.create_index('idx_lead_touchpoints_utm_campaign', 'lead_touchpoints', ['utm_campaign'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('landing_slug', sa.String(), nullable=True),
    sa.Column('landing_url_completa', sa.Text(), nullable=True),
    sa.Column('phone_raw', sa.String(), nullable=True),
    sa.Column('phone_e164', sa.String(), nullable=True),
    sa.Column('email_raw', sa.String(), nullable=True),
    sa.Column('nombre_raw', sa.String(), nullable=True),
    sa.Column('tratamiento_interes', sa.String(), nullable=True),
    sa.Column('utm_source', sa.String(), nullable=True),
    sa.Column('utm_medium', sa.String(), nullable=True),
    sa.Column('utm_campaign', sa.String(), nullable=True),
    sa.Column('utm_content', sa.String(), nullable=True),
    sa.Column('utm_term', sa.String(), nullable=True),
    sa.Column('fbclid', sa.String(), nullable=True),
    sa.Column('gclid', sa.String(), nullable=True),
    sa.Column('consent_marketing', sa.Boolean(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('lead_id', sa.BigInteger(), nullable=True),
    sa.Column('lead_touchpoint_id', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['lead_touchpoint_id'], ['lead_touchpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_form_submissions_fecha_status', 'form_submissions', ['fecha', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_form_submissions_fecha_status', table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index('idx_lead_touchpoints_utm_campaign', table_name='lead_touchpoints')
    op.drop_index('idx_lead_touchpoints_lead_fecha', table_name='lead_touchpoints')
    op.drop_index('idx_lead_touchpoints_fecha', table_name='lead_touchpoints')
    op.drop_table('lead_touchpoints')
    op.drop_index('idx_ventas_fecha', table_name='ventas')
    op.drop_index('idx_ventas_cod_item', table_name='ventas')
    op.drop_index('idx_ventas_cod_cliente_fecha', table_name='ventas')
    op.drop_table('ventas')
    op.drop_index('idx_pagos_tipo_pago', table_name='pagos')
    op.drop_index('idx_pagos_cod_item', table_name='pagos')
    op.drop_index('idx_pagos_cod_cliente_fecha', table_name='pagos')
    op.drop_table('pagos')
    op.drop_index('idx_leads_vtiger_id', table_name='leads')
    op.drop_index('idx_leads_phone_e164', table_name='leads')
    op.drop_index('idx_leads_estado_score', table_name='leads')
    op.drop_index('idx_leads_email_lower', table_name='leads')
    op.drop_table('leads')
    op.drop_index('idx_audit_user_occurred', table_name='audit_log')
    op.drop_index('idx_audit_occurred', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_index('idx_audit_category_occurred', table_name='audit_log')
    op.drop_index('idx_audit_action_occurred', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_user_sessions_user_created', table_name='user_sessions')
    op.drop_index('idx_user_sessions_token_active', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('gastos')
    op.drop_index('idx_dedup_candidates_resuelto', table_name='dedup_candidates')
    op.drop_table('dedup_candidates')
    op.drop_index('idx_clientes_phone_e164', table_name='clientes')
    op.drop_index('idx_clientes_nombre_lower', table_name='clientes')
    op.drop_index('idx_clientes_email_lower', table_name='clientes')
    op.drop_table('clientes')
    op.drop_index('idx_users_username_activo', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_catalogos_lista_activo', table_name='catalogos')
    op.drop_table('catalogos')
    # ### end Alembic commands ###
